global:
  imageRegistry: 208851973471.dkr.ecr.us-east-1.amazonaws.com
namespace: inventory-system
frontend:
  replicaCount: 1
  image:
    tag: 34df8fa
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
backend:
  replicaCount: 1
  image:
    tag: 34df8fa
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 5000
mysql:
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3306
  persistence:
    enabled: true
    storageClass: gp2
    accessMode: ReadWriteOnce
    size: 10Gi
  auth:
    database: inventory_db
    username: inventory_user
    password: Inventory@123
    rootPassword: Root@123
ingress:
  enabled: true
  className: nginx
  host: inventory.local
resources:
  frontend:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi
  backend:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  mysql:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
