apiVersion: v1
kind: Service

metadata:
  name: backend-service
  namespace: {{ .Values.namespace }}
  labels:
    app: ims-backend
    {{- include "inventory-app.labels" . | nindent 4 }}

spec:
  type: {{ .Values.backend.service.type }}

  selector:
    app: ims-backend

  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 5000
      protocol: TCP