apiVersion: v1
kind: Service

metadata:
  name: mysql-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "inventory-app.labels" . | nindent 4 }}

spec:

  selector:
    app: mysql

  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: 3306

  type: {{ .Values.mysql.service.type }}