apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: inventory-app
  namespace: argocd

  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: https://github.com/Dharunr257/enterprise-gitops.git
    targetRevision: main
    path: inventory-app-helm

    helm:
      releaseName: inventory-app

  destination:
    server: https://kubernetes.default.svc
    namespace: inventory-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false

    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 10