apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: inventory-system

resources:
  - namespace.yaml
  - mysql-secret.yaml
  - backend-configmap.yaml
  - mysql-pvc.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml

commonLabels:
  project: enterprise-inventory-platform
  managed-by: kustomize